mongodb:
  image: mongo
  ports:
    - "27017:27017"
  command: mongod --smallfiles --noprealloc
node:
  image: node
  links:
    - mongodb
  ports:
    - "8000:8000"
  volumes:
    - .:/opt
  command: bash -c "cd /opt && npm install && ./node_modules/.bin/bower --allow-root install && CONFIG=docker DEBUG=social-scoreboard* node server/server.js"
